from selenium.webdriver.common.by import By

class OrderPageLocators:
    consent_button = [By.CSS_SELECTOR, 'div[class^=App_CookieConsent] button']
    for_whom_scooter_link = [By.CSS_SELECTOR, 'div[class^=Order_Header]']
    name_field = [By.CSS_SELECTOR, '[class^=Order_Form] [class^=Input_InputContainer]:nth-child(1) input']
    last_name_field = [By.CSS_SELECTOR, '[class^=Order_Form] [class^=Input_InputContainer]:nth-child(2) input']
    address_field = [By.CSS_SELECTOR, '[class^=Order_Form] [class^=Input_InputContainer]:nth-child(3) input']
    metro_station_field = [By.CSS_SELECTOR, '[class^=Order_Form] .select-search input']
    metro_station_name = [By.XPATH, '//div[@class="select-search__select"]//div[text()="Лубянка"]']
    metro_station_name_1 = [By.XPATH, '//div[@class="select-search__select"]//div[text()="Сокол"]']
    telephone_number_field = [By.CSS_SELECTOR, '[class^=Order_Form] [class^=Input_InputContainer]:nth-child(5) input']
    further_button = [By.CSS_SELECTOR, '[class^=Order_NextButton] button']
    rent_header = [By.CSS_SELECTOR, 'div[class^="Order_Header"]']
    time_to_deliver_field = [By.CSS_SELECTOR, '[class^=Order_MixedDatePicker] input']
    date = [By.CLASS_NAME, 'react-datepicker__day--025']
    date_1 = [By.CLASS_NAME, 'react-datepicker__day--028']
    days_of_rent = [By.CSS_SELECTOR, '.Dropdown-root']
    rent_duration = [By.CSS_SELECTOR, '.Dropdown-option:nth-child(3)']
    rent_duration_1 = [By.CSS_SELECTOR, '.Dropdown-option:nth-child(7)']
    scooter_color = [By.CSS_SELECTOR, '[class^=Order_Checkboxes]']
    black_colour = [By.CSS_SELECTOR, '[class^=Order_Checkboxes] [for=black]']
    grey_colour = [By.CSS_SELECTOR, '[class^=Order_Checkboxes] [for=grey]']
    comment_field = [By.CSS_SELECTOR, 'input[placeholder~=Комментарий]']
    order_button_on_page_order = [By.CSS_SELECTOR, '[class^=Order_Buttons] button:last-child']
    back_button = [By.CSS_SELECTOR, '[class^=Order_Buttons] button:first-child']
    do_you_want_to_make_an_order_link = [By.CSS_SELECTOR, '[class^=Order_ModalHeader]']
    yes_button = [By.CSS_SELECTOR, '[class^=Order_Modal] [class^=Order_Buttons] button:last-child']
    no_button = [By.CSS_SELECTOR, '[class^=Order_Modal] [class^=Order_Buttons] button:first-child']
    see_status_button = [By.CSS_SELECTOR, '[class^=Order_NextButton] button']
    order_created = [By.CSS_SELECTOR, '[class^=Order_ModalHeader]']
